/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/raspberry_pi.glb 
Author: Aleksander Buzlaev (https://sketchfab.com/Aleksander2019)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/raspberry-pi-dd04d376b5c24f2a98f4c5dd3ce576a5
Title: Raspberry Pi
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/raspberry_pi.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI, 0, 0]} scale={[1, 0.41, 1]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.main_circuit_board} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Metallic} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Plastic_black} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.ethernet_side_panel_decal} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.led_yellow_off} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.led_lens} />
        <mesh geometry={nodes.Object_10.geometry} material={materials['led_green_off.']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['copper_metal_not_so_shiny.001']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.metal_shiny} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.capacitor_shiny} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.capacitor_center} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.top_nonbroadcom_chip} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.broadcom_chip} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.white_plastic} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.bottom_chip} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Solder} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Solder} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Solder} />
        <mesh geometry={nodes.Object_22.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.metal_shiny_enhanced} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Grey_text_on_chips} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.super_black} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.gold_effect} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.plastic_gloss_black} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.black_chip_procedural} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Material} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.led_component} />
        <mesh geometry={nodes.Object_31.geometry} material={materials.component_FB_shiny} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.component_FB_center} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.resistor_shiny} />
        <mesh geometry={nodes.Object_34.geometry} material={materials['resistor_center.']} />
      </group>
    </group>
  )
}

useGLTF.preload('/raspberry_pi.glb')
